import { string } from 'rollup-plugin-string';
import terser from '@rollup/plugin-terser';
import babel from '@rollup/plugin-babel';
import { nodeResolve } from '@rollup/plugin-node-resolve';
import commonjs from '@rollup/plugin-commonjs';
import replace from '@rollup/plugin-replace';
import { readFileSync, readdirSync, statSync, writeFileSync, existsSync } from 'fs';
import path from 'path';

// Read version from package.json - single source of truth
const pkg = JSON.parse(readFileSync('./package.json', 'utf-8'));
const VERSION = pkg.version;

function generateBundleRegistry() {
  var bundlesDir = path.resolve('bundles');
  var outputFile = path.join(bundlesDir, 'registry.generated.js');

  if (!existsSync(bundlesDir)) {
    return;
  }

  var entries = readdirSync(bundlesDir);
  var bundleDirs = [];

  for (var i = 0; i < entries.length; i++) {
    var entry = entries[i];
    var fullPath = path.join(bundlesDir, entry);
    try {
      if (statSync(fullPath).isDirectory()) {
        var mainPath = path.join(fullPath, 'main.js');
        if (existsSync(mainPath)) {
          bundleDirs.push(entry);
        }
      }
    } catch (err) {
      // Ignore invalid entries
    }
  }

  bundleDirs.sort();

  var lines = [];
  lines.push('/**');
  lines.push(' * AUTO-GENERATED FILE — DO NOT EDIT MANUALLY');
  lines.push(' * Generated by rollup.config.js based on bundles/ folder contents.');
  lines.push(' */');
  lines.push('');

  var bundleMap = [];
  for (var j = 0; j < bundleDirs.length; j++) {
    var name = bundleDirs[j];
    var varName = name.replace(/[^a-zA-Z0-9_$]/g, '_');
    if (varName === 'default') {
      varName = 'defaultBundle';
    }
    lines.push("import " + varName + " from './" + name + "/main.js';");
    bundleMap.push("  '" + name + "': " + varName);
  }

  lines.push('');
  lines.push('export var bundles = {');
  lines.push(bundleMap.join(',\n'));
  lines.push('};');
  lines.push('');
  lines.push('export var bundleNames = Object.keys(bundles);');
  lines.push('');
  lines.push('export default bundles;');
  lines.push('');

  try {
    writeFileSync(outputFile, lines.join('\n'));
  } catch (err) {
    // Ignore write errors
  }
}

// Shared plugins
const plugins = [
  // Generate bundle registry from bundles/ folder at build time
  {
    name: 'bundle-registry-generator',
    buildStart: function() {
      generateBundleRegistry();
    },
  },
  // Replace __VERSION__ placeholder with actual version from package.json
  replace({
    preventAssignment: true,
    values: {
      '__VERSION__': VERSION,
    },
  }),

  // Import CSS files as strings
  string({
    include: '**/*.css',
  }),

  // Resolve imports from node_modules
  nodeResolve({
    browser: true,
    preferBuiltins: false,
  }),

  // Convert CommonJS modules to ES modules
  commonjs({
    include: [/node_modules/],
    transformMixedEsModules: true,
  }),

  // Transpile to ES5 for Chrome 47+ compatibility
  babel({
    babelHelpers: 'bundled',
    presets: [
      ['@babel/preset-env', {
        targets: {
          chrome: '47',
        },
        modules: false,
      }],
    ],
    exclude: 'node_modules/**',
  }),

  // Minify for production
  terser({
    ecma: 5,
    mangle: true,
    compress: {
      drop_console: false, // Keep console.log for diagnostics
    },
  }),
];

export default [
  // Build: TizenPortal universal runtime
  {
    input: 'core/index.js',
    output: {
      file: 'dist/tizenportal.js',
      format: 'iife',
      name: 'TizenPortal',
      sourcemap: false,
    },
    plugins,
  },
];